### PR TITLE
1.12.2/develop update Chat module for msg/tell/r/pm and gmsg logging

### PR DESCRIPTION
**Pull request by Boffinbox**
This update modifies chat logging to log all chat messages received by the server. The goal is to meet any potential compliance issues in the future.

---

Currently, only publicly available messages are logged in the FE chatlog output. It is technically possible to pull all other types of messages from the Minecraft base server `debug.log`, but this is cumbersome to do, and only the five most recent server runs are saved on rotation.

There are server admin issues arising from this. For example, if a few players are in an FE group, and are using their group chat to communicate, this chat is not visible to admins. Unless admins are a direct member of that group, they will not see the contents of this chat. A scenario where this is bad, would be if "trial" members of a server were abusing or spamming using /gmsg. An admin would be unaware of the problem, and unable to check chatlogs to verify afterwards.

Or, on a more serious note, there are safeguarding concerns regarding abuse that could happen through private messages on a server. In the unlikely event of such a case, it would be desirable to have access to PM and whisper logs that could be checked, and if relevant, turned over to authorities.

---

This PR adds logging for these categories, enabled by default, and included as part of the FE chat logging module. It comes with config options available in `Chat.cfg` that allow toggling of the individual types of logging: `LogChat`, `LogGroupChats`, and `LogTells`.

If any one of these three options is enabled, then FE chat logging is enabled for that category, and all three types write to the same file in sequence. If and only if all three options are set to `false`, then log file output is disabled entirely.

Logging for all three types is enabled by default, in case there is a compliance reason in the future. If the end-user chooses to disable logging, that's their prerogative, and it's not FE's fault. But, the option should be there for privacy conscious server admins, who perhaps run the server from jurisdictions that don't care.

### CODE REVIEW

File: src/main/java/com/forgeessentials/chat/irc/IrcHandler.java
Comment (spacebuilder2020) [inline src/main/java/com/forgeessentials/chat/irc/IrcHandler.java:1]: Might be wise to do this for the discord handler as well.
https://github.com/ForgeEssentials/ForgeEssentials/blob/1.12.2/develop/src/main/java/com/forgeessentials/chat/discord/DiscordHandler.java

**Review by spacebuilder2020 — APPROVED** [review]
Looks good, one comment about doing logging for the discord module below.

File: src/main/java/com/forgeessentials/chat/irc/IrcHandler.java
Comment (Boffinbox) [reply src/main/java/com/forgeessentials/chat/irc/IrcHandler.java:1]: Ah, good spot. It's also made me realise I should double check how this is being handled in the IRC module.

For the IRC one, I did a simple search for previous logging, and then modified to work with the new config. However, for the IRC (and Discord too!) I should look closely as to how that sends and receives messages.

I will check this on Friday 21st, and hopefully have a new commit ready by EOD

Comment (Boffinbox) [reply src/main/java/com/forgeessentials/chat/irc/IrcHandler.java:1]: Okay, I've got the IRC chat logging working correctly, such that if the server has a combo of `LogTells` and `LogIRC`, the correct messages are logged only.

For example, if a user has IRC logging enabled, but PM logging disabled, only the _publicly viewable_ IRC chats would come through.

Or, if IRC logging is switched off, and PM logging is switched on, that means that PMs from IRC won't be included in the log.

Comment (Boffinbox) [reply src/main/java/com/forgeessentials/chat/irc/IrcHandler.java:1]: As for the Discord logging, I cannot test because there seems to be a problem with the Discord integration, which is currently above my expertise to solve. Discord integration works in 1.7.10, but does not work in 1.12.2.

The culprit is something along these lines:
```
...
[20:13:49] [Thread-6/INFO] [STDERR]: [org.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
[20:13:49] [Thread-6/INFO] [STDERR]: [org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation MDCAdapter implementation.
[20:13:49] [Thread-6/INFO] [STDERR]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[20:13:49] [Server thread/ERROR] [FML]: Exception caught during firing event com.forgeessentials.util.events.FEModuleEvent$FEModuleInitEvent@56bde15b:
java.lang.NoClassDefFoundError: org/apache/commons/collections4/map/CaseInsensitiveMap
    at net.dv8tion.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:78) ~[JDALogger.class:5.0.0-beta.8]
    at net.dv8tion.jda.internal.utils.IOUtil.<clinit>(IOUtil.java:40) ~[IOUtil.class:5.0.0-beta.8]
    at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1787) ~[JDABuilder.class:5.0.0-beta.8]
    at com.forgeessentials.chat.discord.DiscordHandler.load(DiscordHandler.java:119) ~[DiscordHandler.class:?]
...
```

So, for now, I can't add the Discord logging on this PR. I'll switch to working on #2684 for that.

**Comment by spacebuilder2020** [comment]
Btw, @Boffinbox I wanted to give you an update.  I fixed the issue with discord.

It was a nasty set of classloader issues due to complex logic in the LaunchClassloader.

(the libraries were there but the classloader was either ignoring them on a class basis, or asking the parent classloader for classes that matched a broad exclusion.  ex: `org.apache.commons`)
The solution for the latter was to add the library to the parent classloader and the solution for ignoring classes was to remove them from the invalid and negative resource caches.

See https://github.com/ForgeEssentials/ForgeEssentials/pull/2691/files
